In [1]:
import pandas as pd 
df = pd.read_csv("../data/pakwheels_used_cars.csv")

In [2]:
df.head()

,ad_ref,assembly,body,ad_city,color,engine_cc,fuel_type,make,mileage,model,registered,transmission,year,price
0,7927285,Imported,Van,Lahore,Pearl White,2000.0,Hybrid,Nissan,124000,Serena,Un-Registered,Automatic,1905.0,8990000.0
1,7679303,Imported,Hatchback,Lahore,Grey,996.0,Petrol,Toyota,30738,Vitz,Punjab,Automatic,1905.0,4190000.0
2,7915479,NaN,Sedan,Lahore,Super white,1798.0,Petrol,Toyota,183000,Corolla,Punjab,Automatic,1905.0,3990000.0
3,7918380,NaN,Sedan,Lahore,Crystal Black Pearl,1500.0,Petrol,Honda,41000,Civic,Punjab,Automatic,1905.0,6490000.0
4,7676167,Imported,MPV,Lahore,Silver,3000.0,Petrol,Toyota,126000,Alphard,Punjab,Automatic,1905.0,4750000.0

In [3]:
df.shape

(77237, 14)

In [4]:
df.columns

Index(['ad_ref', 'assembly', 'body', 'ad_city', 'color', 'engine_cc',
       'fuel_type', 'make', 'mileage', 'model', 'registered', 'transmission',
       'year', 'price'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 77237 entries, 0 to 77236
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ad_ref        77237 non-null  int64
 1   assembly      23976 non-null  str
 2   body          68372 non-null  str
 3   ad_city       77237 non-null  str
 4   color         75727 non-null  str
 5   engine_cc     77235 non-null  float64
 6   fuel_type     76303 non-null  str
 7   make          77237 non-null  str
 8   mileage       77237 non-null  int64
 9   model         77237 non-null  str
 10  registered    77237 non-null  str
 11  transmission  77237 non-null  str
 12  year          72516 non-null  float64
 13  price         76588 non-null  float64
dtypes: float64(3), int64(2), str(9)
memory usage: 12.4 MB

In [6]:
df.isnull().sum()

ad_ref              0
assembly        53261
body             8865
ad_city             0
color            1510
engine_cc           2
fuel_type         934
make                0
mileage             0
model               0
registered          0
transmission        0
year             4721
price             649
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

             ad_ref     engine_cc         mileage     year         price
count  7.723700e+04  77235.000000    77237.000000  72516.0  7.658800e+04
mean   7.797474e+06   1406.452062    91296.829589   1905.0  3.854193e+06
std    2.569679e+05    707.665165    89705.138633      0.0  5.576970e+06
min    2.748970e+05      3.000000        1.000000   1905.0  1.200000e+05
25%    7.792632e+06   1000.000000    34000.000000   1905.0  1.425000e+06
50%    7.853515e+06   1300.000000    80000.000000   1905.0  2.650000e+06
75%    7.897048e+06   1600.000000   123456.000000   1905.0  4.500000e+06
max    7.931906e+06  15000.000000  1000000.000000   1905.0  1.800000e+08

In [9]:
df["year"].dtype
df["year"].head(10)
df["year"].value_counts().head(10)

year
1905.0    72516
Name: count, dtype: int64

In [13]:
raw = pd.read_csv("../data/pakwheels_used_cars.csv", dtype=str, nrows=5)
print(raw["year"])

0    1905
1    1905
2    1905
3    1905
4    1905
Name: year, dtype: str

In [14]:
df = df.drop(columns=["ad_ref", "year"])

In [2]:
import pandas as pd

df = pd.read_csv("../data/pakwheels_used_cars.csv")

In [3]:
print(df["price"].quantile([0.01, 0.05, 0.5, 0.95, 0.99]))
print(df["mileage"].quantile([0.01, 0.05, 0.5, 0.95, 0.99]))
print(df["mileage"].value_counts().head(10))
print(df["engine_cc"].value_counts().head(15))
print(df[["make", "model", "ad_city", "registered", "transmission"]].nunique())
print(df["fuel_type"].value_counts())
print(df["make"].value_counts().head(10))

0.01      325000.0
0.05      600000.0
0.50     2650000.0
0.95     9500000.0
0.99    22500000.0
Name: price, dtype: float64
0.01         1.00
0.05       900.00
0.50     80000.00
0.95    210000.00
0.99    398808.96
Name: mileage, dtype: float64
mileage
100000    3600
150000    2003
200000    1635
80000     1339
90000     1087
120000     985
50000      976
70000      951
123456     945
85000      836
Name: count, dtype: int64
engine_cc
1300.0    14080
1000.0    13150
1500.0     8673
1800.0     7949
660.0      7777
800.0      6127
1600.0     4029
2000.0     1537
796.0      1304
2800.0     1282
2700.0     1180
3000.0     1025
1999.0      885
1798.0      790
1200.0      720
Name: count, dtype: int64
make             69
model           432
ad_city         297
registered      128
transmission      2
dtype: int64
fuel_type
Petrol    70028
Diesel     3444
Hybrid     2831
Name: count, dtype: int64
make
Toyota        24678
Suzuki        22322
Honda         16270
Daihatsu       3143
KIA            1687
Nissan         1524
Hyundai        1449
Mitsubishi     1098
Changan         933
Mercedes        615
Name: count, dtype: int64

In [4]:
df.columns

Index(['ad_ref', 'assembly', 'body', 'ad_city', 'color', 'engine_cc',
       'fuel_type', 'make', 'mileage', 'model', 'registered', 'transmission',
       'year', 'price'],
      dtype='str')

In [5]:
df = df.drop(columns=["ad_ref", "year"])

In [6]:
df.columns

Index(['assembly', 'body', 'ad_city', 'color', 'engine_cc', 'fuel_type',
       'make', 'mileage', 'model', 'registered', 'transmission', 'price'],
      dtype='str')

In [7]:
df = df.dropna(subset=["price", "engine_cc"])

In [8]:
df.isnull().sum()

assembly        52925
body             8814
ad_city             0
color            1446
engine_cc           0
fuel_type         910
make                0
mileage             0
model               0
registered          0
transmission        0
price               0
dtype: int64

In [9]:
for col in ["assembly", "body", "color", "fuel_type"]:
    df[col] = df[col].fillna("Unknown")

In [10]:
df[["assembly", "body", "color", "fuel_type"]].isnull().sum()

assembly     0
body         0
color        0
fuel_type    0
dtype: int64

In [11]:
n_start = len(df)

print(n_start)

76586

In [12]:
print("Rows before:", len(df))

df = df[df["mileage"] != 123456]

print("Rows after:", len(df))

Rows before: 76586
Rows after: 75641

In [13]:
print("Rows before:", len(df))

df = df[df["mileage"].between(100, 400000)]

print("Rows after:", len(df))

Rows before: 75641
Rows after: 72559

In [14]:
print("Rows before:", len(df))

df = df[df["engine_cc"].between(600, 6000)]

print("Rows after:", len(df))

Rows before: 72559
Rows after: 72370

In [15]:
lo, hi = df["price"].quantile([0.01, 0.99])

print("Lower limit:", lo)
print("Upper limit:", hi)

Lower limit: 330000.0
Upper limit: 20530999.99999977

In [16]:
print("Rows before:", len(df))

df = df[df["price"].between(lo, hi)]

print("Rows after:", len(df))

Rows before: 72370
Rows after: 70970

In [17]:
print(f"Started with {n_start} rows")
print(f"Ended with {len(df)} rows")
print(f"Kept {len(df) / n_start:.1%} of the data")

Started with 76586 rows
Ended with 70970 rows
Kept 92.7% of the data

In [19]:
df.to_csv("../data/cleaned_cars.csv", index=False)

In [20]:
df["mileage"].describe()

count     70970.000000
mean      88911.346851
std       65041.893149
min         100.000000
25%       38000.000000
50%       81000.000000
75%      123000.000000
max      400000.000000
Name: mileage, dtype: float64

In [21]:
df["engine_cc"].describe()

count    70970.000000
mean      1379.048429
std        605.847762
min        600.000000
25%       1000.000000
50%       1300.000000
75%       1600.000000
max       6000.000000
Name: engine_cc, dtype: float64

In [22]:
df["price"].describe()

count    7.097000e+04
mean     3.448469e+06
std      2.842367e+06
min      3.300000e+05
25%      1.495000e+06
50%      2.700000e+06
75%      4.450000e+06
max      2.050000e+07
Name: price, dtype: float64