In [1]:
import pandas as pd 
df = pd.read_csv("../data/pakwheels_used_cars.csv")

In [2]:
df.head()

,ad_ref,assembly,body,ad_city,color,engine_cc,fuel_type,make,mileage,model,registered,transmission,year,price
0,7927285,Imported,Van,Lahore,Pearl White,2000.0,Hybrid,Nissan,124000,Serena,Un-Registered,Automatic,1905.0,8990000.0
1,7679303,Imported,Hatchback,Lahore,Grey,996.0,Petrol,Toyota,30738,Vitz,Punjab,Automatic,1905.0,4190000.0
2,7915479,NaN,Sedan,Lahore,Super white,1798.0,Petrol,Toyota,183000,Corolla,Punjab,Automatic,1905.0,3990000.0
3,7918380,NaN,Sedan,Lahore,Crystal Black Pearl,1500.0,Petrol,Honda,41000,Civic,Punjab,Automatic,1905.0,6490000.0
4,7676167,Imported,MPV,Lahore,Silver,3000.0,Petrol,Toyota,126000,Alphard,Punjab,Automatic,1905.0,4750000.0

In [3]:
df.shape

(77237, 14)

In [4]:
df.columns

Index(['ad_ref', 'assembly', 'body', 'ad_city', 'color', 'engine_cc',
       'fuel_type', 'make', 'mileage', 'model', 'registered', 'transmission',
       'year', 'price'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 77237 entries, 0 to 77236
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ad_ref        77237 non-null  int64
 1   assembly      23976 non-null  str
 2   body          68372 non-null  str
 3   ad_city       77237 non-null  str
 4   color         75727 non-null  str
 5   engine_cc     77235 non-null  float64
 6   fuel_type     76303 non-null  str
 7   make          77237 non-null  str
 8   mileage       77237 non-null  int64
 9   model         77237 non-null  str
 10  registered    77237 non-null  str
 11  transmission  77237 non-null  str
 12  year          72516 non-null  float64
 13  price         76588 non-null  float64
dtypes: float64(3), int64(2), str(9)
memory usage: 12.4 MB

In [6]:
df.isnull().sum()

ad_ref              0
assembly        53261
body             8865
ad_city             0
color            1510
engine_cc           2
fuel_type         934
make                0
mileage             0
model               0
registered          0
transmission        0
year             4721
price             649
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

             ad_ref     engine_cc         mileage     year         price
count  7.723700e+04  77235.000000    77237.000000  72516.0  7.658800e+04
mean   7.797474e+06   1406.452062    91296.829589   1905.0  3.854193e+06
std    2.569679e+05    707.665165    89705.138633      0.0  5.576970e+06
min    2.748970e+05      3.000000        1.000000   1905.0  1.200000e+05
25%    7.792632e+06   1000.000000    34000.000000   1905.0  1.425000e+06
50%    7.853515e+06   1300.000000    80000.000000   1905.0  2.650000e+06
75%    7.897048e+06   1600.000000   123456.000000   1905.0  4.500000e+06
max    7.931906e+06  15000.000000  1000000.000000   1905.0  1.800000e+08

In [9]:
df["year"].dtype
df["year"].head(10)
df["year"].value_counts().head(10)

year
1905.0    72516
Name: count, dtype: int64

In [13]:
raw = pd.read_csv("../data/pakwheels_used_cars.csv", dtype=str, nrows=5)
print(raw["year"])

0    1905
1    1905
2    1905
3    1905
4    1905
Name: year, dtype: str

In [14]:
df = df.drop(columns=["ad_ref", "year"])